# Generated by Django 4.1.1 on 2022-09-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0002_alter_like_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='like_count',
            new_name='like_counts',
        ),
        migrations.AddField(
            model_name='post',
            name='like_users',
            field=models.ManyToManyField(related_name='myLikePosts', through='postapp.Like', to='postapp.userinfo'),
        ),
    ]
