# Generated by Django 4.1.1 on 2022-09-30 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postapp', '0003_rename_like_count_post_like_counts_post_like_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='major_main',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='major_sub',
        ),
        migrations.AlterField(
            model_name='like',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myPost', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='like_users',
            field=models.ManyToManyField(related_name='myLikePosts', through='postapp.Like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Major',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
